// Generated by CoffeeScript 2.7.0
(function() {
  // Calculator functions
  var add, appendToDisplay, calculate, clearDisplay, divide, multiply, subtract, updateDisplay;

  add = function(a, b) {
    return a + b;
  };

  subtract = function(a, b) {
    return a - b;
  };

  multiply = function(a, b) {
    return a * b;
  };

  divide = function(a, b) {
    if (b === 0) {
      return 'Error';
    } else {
      return a / b;
    }
  };

  // Update the display with the result
  updateDisplay = function(value) {
    return document.getElementById("display").value = value;
  };

  // Clear the display
  clearDisplay = function() {
    return document.getElementById("display").value = '';
  };

  // Function to append numbers to the display
  appendToDisplay = function(value) {
    var displayValue;
    displayValue = document.getElementById("display").value;
    return document.getElementById("display").value = displayValue + value;
  };

  // Function to calculate the result
  calculate = function() {
    var displayValue, error, result;
    displayValue = document.getElementById("display").value;
    try {
      result = eval(displayValue); // Convert expression to actual result
      return updateDisplay(result);
    } catch (error1) {
      error = error1;
      return updateDisplay('Error');
    }
  };

  // Event listeners for buttons
  document.getElementById("btn1").onclick = function() {
    return appendToDisplay('1');
  };

  document.getElementById("btn2").onclick = function() {
    return appendToDisplay('2');
  };

  document.getElementById("btn3").onclick = function() {
    return appendToDisplay('3');
  };

  document.getElementById("btn4").onclick = function() {
    return appendToDisplay('4');
  };

  document.getElementById("btn5").onclick = function() {
    return appendToDisplay('5');
  };

  document.getElementById("btn6").onclick = function() {
    return appendToDisplay('6');
  };

  document.getElementById("btn7").onclick = function() {
    return appendToDisplay('7');
  };

  document.getElementById("btn8").onclick = function() {
    return appendToDisplay('8');
  };

  document.getElementById("btn9").onclick = function() {
    return appendToDisplay('9');
  };

  document.getElementById("btn0").onclick = function() {
    return appendToDisplay('0');
  };

  document.getElementById("btnAdd").onclick = function() {
    return appendToDisplay('+');
  };

  document.getElementById("btnSubtract").onclick = function() {
    return appendToDisplay('-');
  };

  document.getElementById("btnMultiply").onclick = function() {
    return appendToDisplay('*');
  };

  document.getElementById("btnDivide").onclick = function() {
    return appendToDisplay('/');
  };

  document.getElementById("btnClear").onclick = clearDisplay;

  document.getElementById("btnEqual").onclick = calculate;

}).call(this);
